version: "3.7"

services: 
    mysql:
        build: ./docker/mysql
        container_name: todo-db
        environment: 
            - MYSQL_ROOT_PASSWORD=golang
            - TZ=Asia/Tokyo
        volumes: 
            - ./mysql/init:/docker-entrypoint-initdb.d
            - ./mysql/data/:/var/lib/mysql
        ports: 
            - "3306:3306"

    app:
        build: ./docker/go
        tty: true
        container_name: todo
        environment: 
            - TZ=Asia/Tokyo
        ports: 
            - "8080:8080"
        volumes: 
            - ./:/go/src/todo/
        depends_on: 
            - mysql


